export const metricNames = ["inputTotalTokens", "inputUncachedTokens", "cacheReadTokens", "cacheWriteTokens", "outputTotalTokens", "reasoningOutputTokens", "totalTokens"] as const;
export type MetricName = typeof metricNames[number];
export type UsageMetrics = Record<MetricName, number | null>;
export type UsageObservation = {
  eventId: string;
  sourceId: string;
  sourceVersion: string;
  scope: "model_request" | "turn" | "provider_session" | "interval" | "unknown";
  semantics: "delta" | "cumulative" | "snapshot" | "unknown";
  coverageId: string;
  invocationId: string | null;
  executionId: string | null;
  providerEpochId: string;
  occurredAt: string | null;
  intervalStart?: string;
  finality: "interim" | "final" | "unknown";
  revision: number;
  measurement: "reported" | "derived" | "estimated";
  normalizationProfile: string | null;
  metrics: Partial<UsageMetrics>;
  runtimeKind?: string;
  model?: string | null;
  sourcePriority?: number;
  correctionReason?: string;
};
export type UsageBinding = { namespace: string; agentId: string; sessionId: string; generation: number };
export type UsageFilter = { namespace?: string; agentId?: string; sessionId?: string; from?: string; to?: string; runtimeKind?: string };
export type UsageRecord = UsageObservation & UsageBinding & { metrics: UsageMetrics; issues?: string[] };
export type UsageSummary = {
  usage: UsageMetrics;
  unplacedUsage: UsageMetrics;
  locatedUsage: UsageMetrics;
  accountingBasis: "none" | "model_requests" | "turn_totals" | "range_totals" | "interval_totals" | "mixed";
  completeness: "none" | "partial" | "complete" | "conflict";
  observedModelRequests: number;
  requestsWithCompleteUsage: number;
  requestsWithMissingUsage: number;
  requestsWithPartialUsage: number;
  unverifiedObservations: number;
  conflictingRanges: number;
  asOf: string;
};
