import { createHmac } from "node:crypto";

import { constantTimeTokenEqual } from "../../auth.js";
import { requiredWebhookHeader, webhookHeader, webhookPayload, type WebhookAdapter } from "./adapter.js";

const signingKey = (secret: string): Buffer | undefined => {
  if (!secret.startsWith("whsec_")) return undefined;
  const encoded = secret.slice("whsec_".length);
  const key = Buffer.from(encoded, "base64");
  return key.length > 0 && key.toString("base64") === encoded ? key : undefined;
};

export const gitlabWebhookAdapter: WebhookAdapter = {
  definition: {
    id: "gitlab", name: "GitLab", authModes: ["signature", "token"],
    secretHint: {
      zh: "签名验证：粘贴 GitLab 生成的 Signing token（whsec_ 开头）。旧版选择 Token 验证，并填写与平台 Secret token 相同的值。",
      en: "Signature: paste the Signing token generated by GitLab (whsec_ prefix). For older versions, choose Token and enter the matching Secret token."
    }
  },
  validateSecret: (secret, mode) => mode === "token" || signingKey(secret) !== undefined,
  authenticate({ headers, body }, secret, mode) {
    if (mode === "token") {
      const token = headers["x-gitlab-token"];
      return typeof token === "string" && constantTimeTokenEqual(secret, token);
    }
    const key = signingKey(secret);
    const id = webhookHeader(headers, "webhook-id");
    const timestamp = webhookHeader(headers, "webhook-timestamp");
    const signatures = webhookHeader(headers, "webhook-signature");
    if (key === undefined || id === undefined || timestamp === undefined || signatures === undefined || !/^\d+$/.test(timestamp)) return false;
    const seconds = Number(timestamp);
    if (!Number.isSafeInteger(seconds) || Math.abs(Date.now() / 1000 - seconds) > 300) return false;
    const expected = `v1,${createHmac("sha256", key).update(`${id}.${timestamp}.`).update(body).digest("base64")}`;
    return signatures.split(/\s+/).some((signature) => constantTimeTokenEqual(expected, signature));
  },
  normalize(request) {
    return {
      eventType: requiredWebhookHeader(request.headers, "x-gitlab-event"),
      deliveryId: requiredWebhookHeader(request.headers, "webhook-id", "idempotency-key", "x-gitlab-webhook-uuid"),
      payload: webhookPayload(request)
    };
  }
};
